brew "anomalyco/tap/opencode", trusted: true
brew "autopep8"
brew "bun"
brew "gh"
brew "htop"
brew "neovim"
brew "node"
brew "tailscale"
brew "the_silver_searcher"
brew "yarn"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "google-chrome"
cask "iterm2"
tap "anomalyco/tap"
